name: async_profiler
description: Profile async function
repository: https://github.com/rajmaniar/async_profiler
version: 0.0.1
dependencies:
  stack_trace: '^1.9.6'

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
